version: "3.8"
services:
  transaction-api:
    build:
      context: ./transaction-api
      dockerfile: Dockerfile
    image: transaction-api:local
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: notification-service:local
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
